### ISSUE TITLE
Where to find Swagger

### ISSUE THREAD

**Issue by pepebotika69** [khepin/php-grpc-server-notes#9]
Hi!

Maybe a silly question, but where con I find Swagger? I tried http://localhost:8080/swagger, but I got: Not Found.

I see there is a file simplecache.swagger.json and my IDE shows me the description

 ![Screenshot from 2021-11-11 22-41-19](https://user-images.githubusercontent.com/14938095/141358833-5a187c41-df33-46b6-8e5c-d8cdf085ce57.png)

But is it possible to see it from browser?

**Comment by khepin** [comment]
There's nothing in the project to render a swagger file. You can try https://editor.swagger.io/ or figure out if there's other solutions that might integrate better.

**Comment by pepebotika69** [comment]
Ok.thanks!
